### ISSUE TITLE
How to copy file to hdfs

### ISSUE THREAD

**Issue by sashasofa** [suraj95/Spark-on-Docker#1]
Hi 

When trying to copy  file to hdfs  with "hdfs dfs -copyFromLocal /tmp/loan.csv /user/thenson/loan.csv"

Inside sparks master docker , I get :
ERROR: JAVA_HOME is not set and could not be found

Please help

Thanks
Sasha

**Comment by IbrarMakaveli** [comment]
Hello,

It's not big deal, you have just to find JDK install in /usr/lib, and set JAVA_HOME.

Try : export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64

Ibrar
