### ISSUE TITLE
SOLVED: Reverse proxy ERROR: listen tcp 0.0.0.0:80: bind: address already in use

### ISSUE THREAD

**Issue by SuperElectron** [suraj95/Spark-on-Docker#2]
I got this error after executing ```./build_cluster.sh ``` and solved it.  
__This could be added into the README.md.__

- here is the error

```bash
ERROR: for reverse-proxy  Cannot start service reverse-proxy: driver failed programming external connectivity on endpoint spark-on-docker_reverse-proxy_1 (ec98d86fdb5f6ca598e0e8420aeb120725dc326d863380325103b507873a0049): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

- I solved this by stopping one of the two services 
- you can look and see on your cpu which is being used from a previous project!

```bash
sudo service nginx stop 
sudo service apache2 stop
```

Great job on the introductory project and thank you for the article: https://towardsdatascience.com/building-a-scalable-spark-cluster-with-docker-containers-f921d860fa46

**Comment by suraj95** [comment]
You're welcome ! :)
